<?php
if( !defined('PSZAPP_INIT') ) exit;

/*
*	Language	: English
*	Code		: EN
*	Translator	: Phong Thai
*	Contact		: https://tooly.win - prescriptz.com@gmail.com
*/

/*
** Instructions to translate this file to your language

 - Please DO NOT translate:
 	+ $lang indexes
 	+ Text links
 	+ Language codes
 	+ PHP variables, PHP function parameters
 	+ Uppercase strings in braces
 - Please KEEP:
 	+ formats of UPPERCASE / lowercase
 	+ the order of arrays

 - Samples:
/////
$lang['do not translate this part'] = 'Please translate this part to your language';
$lang['index - do not translate']   = 'Translate but leave <a href="/do-not-translate/">translate here, too</a>, keep translating';
$lang['index - do not']             = 'Translate outside {{DO-NOT-TRANSLATE}} and translate this too';

$lang['index - do not']             = array('Translate this part 1', 'Translate this part 2', 'Translate this part 3');
$lang['index - do not']             = array('Translate this index'	=> 'Translate this value, too');
/////
*/

$lang['Text & HEX Converter'] = 'Text & HEX Converter';
$lang['Simple, free, easy and powerful tool to convert between a string and hexadecimal, may enter a link, video or image to encode/decode; even you may do with the remote URLs or upload your own files, also download as well or share your friends directly with their own languages.'] = 'Simple, free, easy and powerful to to convert between a string and hexadecimal, may enter a link, video or image to encode/decode; even you may do with the remote URLs or upload your own files, also download as well or share your friends directly with their own languages.';
$lang['string to hexadecimal, string to hex, text to hex, text to hex converter, word to hexadecimal converter,word to hex converter, text to hexadecimal generator, text to hex online, plain text to hex converter, translate english to hexadecimal, convert file to hex, convert url to hex, decode video from hex, decode link from hex, hex code from url'] = 'string to hexadecimal, string to hex, text to hex, text to hex converter, word to hexadecimal converter,word to hex converter, text to hexadecimal generator, text to hex online, plain text to hex converter, translate english to hexadecimal, convert file to hex, convert url to hex, decode video from hex, decode link from hex, hex code from url';

$lang['This tool currently does not support the GET method'] = 'This tool currently does not support the GET method';
$lang['Missing input'] = 'Missing input';
$lang['your plain text you would like to encode'] = 'your plain text you would like to encode';
$lang['your encoded data'] = 'your encoded data';
$lang['Number of latest tasks'] = 'Number of latest tasks';
$lang['This sets the number of tasks'] = 'This sets the number of tasks';
$lang['What is the difference between a Hexadecimal and a Decimal?'] = 'What is the difference between a Hexadecimal and a Decimal?';
$lang['The hexadecimal system is a base 16 number notation, while the decimal system is a base 10 number notation. In other words, the hexadecimal system uses 16 symbols to represent numbers, while the decimal system uses 10 symbols. This expansion also allows for a higher information density-hexadecimal digits can represent twice as many values as decimal digits.'] = 'The hexadecimal system is a base 16 number notation, while the decimal system is a base 10 number notation. In other words, the hexadecimal system uses 16 symbols to represent numbers, while the decimal system uses 10 symbols. This expansion also allows for a higher information density-hexadecimal digits can represent twice as many values as decimal digits.';
$lang['Hexadecimal numbers are made up of 16 digits instead of the 10 in a decimal number. The order of these numbers starts over after F (or 15 in decimal), while it doesn’t in the decimals. Check out the table below to see how they compare!'] = 'Hexadecimal numbers are made up of 16 digits instead of the 10 in a decimal number. The order of these numbers starts over after F (or 15 in decimal), while it doesn’t in the decimals. Check out the table below to see how they compare!';
$lang['How do you convert a Hexadecimal to a Decimal?'] = 'How do you convert a Hexadecimal to a Decimal?';
$lang['When converting hexadecimal to decimal, the first step is to divide the hex number by 16. This will give you the base number. The second step is to divide each digit of the hex number by 16 and write down the results. Finally, add up all of the numbers that were just calculated.'] = 'When converting hexadecimal to decimal, the first step is to divide the hex number by 16. This will give you the base number. The second step is to divide each digit of the hex number by 16 and write down the results. Finally, add up all of the numbers that were just calculated.';
$lang['For example, if someone wants to convert 9F7A to decimal, they would first divide 9F7A by 16 which equals 6051. Then they would divide each digit of 6051 by 16 which equals 381. Lastly, they would add up 381 + 381 + 381 which equals 1144. Therefore, 9F7A in decimal is equal to 1144'] = 'For example, if someone wants to convert 9F7A to decimal, they would first divide 9F7A by 16 which equals 6051. Then they would divide each digit of 6051 by 16 which equals 381. Lastly, they would add up 381 + 381 + 381 which equals 1144. Therefore, 9F7A in decimal is equal to 1144';
$lang['How do you convert a Decimal to a Hexadecimal?'] = 'How do you convert a Decimal to a Hexadecimal?';
$lang['Converting decimal to hexadecimal is a simple process, and can be done with a calculator or online converter. In order to convert the number, divide it by 16 and take the remainder. This remainder will then correspond to a hexadecimal digit. For example, if you have the decimal number 234, divide it by 16 and take the remainder: 234 / 16 = 14 R 2. Therefore, in hexadecimal notation, this number would be written as “E2”.'] = 'Converting decimal to hexadecimal is a simple process, and can be done with a calculator or online converter. In order to convert the number, divide it by 16 and take the remainder. This remainder will then correspond to a hexadecimal digit. For example, if you have the decimal number 234, divide it by 16 and take the remainder: 234 / 16 = 14 R 2. Therefore, in hexadecimal notation, this number would be written as “E2”.';
$lang['There are many tools available online that can help with converting between decimal and hexadecimal numbers. Additionally, most calculators have a built-in function that will allow you to do this conversion very easily. With just a few clicks of the mouse or taps on the keyboard, you’ll be able to change any decimal value into its corresponding hexadecimal equivalent!'] = 'There are many tools available online that can help with converting between decimal and hexadecimal numbers. Additionally, most calculators have a built-in function that will allow you to do this conversion very easily. With just a few clicks of the mouse or taps on the keyboard, you’ll be able to change any decimal value into its corresponding hexadecimal equivalent!';
$lang['What are the benefits of using a Hexadecimal over a Decimal?'] = 'What are the benefits of using a Hexadecimal over a Decimal?';
$lang['The hexadecimal, or base-16, system was designed to emulate some of the same properties as the decimal system. In other words, it was created to make things easier for us humans. The number 423 has 16 digits instead of 10 digits available in a decimal system. This is because hexadecimal uses a base of 16 symbols instead of 10. After F, the order begins again with 0 and so on and so forth until we get to 15 which is notated as F.'] = 'The hexadecimal, or base-16, system was designed to emulate some of the same properties as the decimal system. In other words, it was created to make things easier for us humans. The number 423 has 16 digits instead of 10 digits available in a decimal system. This is because hexadecimal uses a base of 16 symbols instead of 10. After F, the order begins again with 0 and so on and so forth until we get to 15 which is notated as F.';
$lang['Hexadecimal encoding reduces the number of digits by a factor of eight when compared to the decimal system. Additionally, hexadecimal numbers have an information density that is twice as high as decimal numbers do. So, why should you bother learning this funky little numbering scheme? Because it can make your life easier! When working with digital systems or data transmission, using hex will save you time and energy when decoding cryptic messages or data streams.'] = 'Hexadecimal encoding reduces the number of digits by a factor of eight when compared to the decimal system. Additionally, hexadecimal numbers have an information density that is twice as high as decimal numbers do. So, why should you bother learning this funky little numbering scheme? Because it can make your life easier! When working with digital systems or data transmission, using hex will save you time and energy when decoding cryptic messages or data streams.';
$lang['What are the benefits of using a Decimal over a Hexadecimal?'] = 'What are the benefits of using a Decimal over a Hexadecimal?';
$lang['When it comes to binary coding, Hexadecimal is more efficient because it reduces 8 digits to 2. Additionally, Hex provides a greater degree of information density and higher accuracy in numbers than binary does. This is due to the fact that Hex uses 16 symbols instead of just two like binary. Because of this increased efficiency, Hexadecimal is often used when binary coding in computing and digital electronics as well as for computer science applications.'] = 'When it comes to binary coding, Hexadecimal is more efficient because it reduces 8 digits to 2. Additionally, Hex provides a greater degree of information density and higher accuracy in numbers than binary does. This is due to the fact that Hex uses 16 symbols instead of just two like binary. Because of this increased efficiency, Hexadecimal is often used when binary coding in computing and digital electronics as well as for computer science applications.';
$lang['In addition, Hexadecimal takes up less space than decimal. With only two digits instead of 8 binary digits, Hex numbers represent large numbers much more concisely. This can be very helpful when working with computer systems, as there is less chance for mistakes when typing in hex codes compared to decimal codes which have so many decimal points all over the place!'] = 'In addition, Hexadecimal takes up less space than decimal. With only two digits instead of 8 binary digits, Hex numbers represent large numbers much more concisely. This can be very helpful when working with computer systems, as there is less chance for mistakes when typing in hex codes compared to decimal codes which have so many decimal points all over the place!';
$lang['What is the range of values that can be represented by a Hexadecimal?'] = 'What is the range of values that can be represented by a Hexadecimal?';
$lang['A hexadecimal number is a number that uses 16 digits instead of the 10 digits we use in the decimal system. This number system is called base-16, and it helps us to emulate the properties of our familiar decimal system. In hexadecimal, each digit represents a power of 16. The numbers 0 through 9 represent the powers of 1 through 10, while A through F represent the powers of 11 through 15.'] = 'A hexadecimal number is a number that uses 16 digits instead of the 10 digits we use in the decimal system. This number system is called base-16, and it helps us to emulate the properties of our familiar decimal system. In hexadecimal, each digit represents a power of 16. The numbers 0 through 9 represent the powers of 1 through 10, while A through F represent the powers of 11 through 15.';
$lang['Just like in decimal, after 16 symbols have been used in Hexadecimal, the order of numbers starts over again at zero. So, hexadecimal 10 is equal to decimal 16, and hexadecimal 11 is equal to decimal 17. And so on!'] = 'Just like in decimal, after 16 symbols have been used in Hexadecimal, the order of numbers starts over again at zero. So, hexadecimal 10 is equal to decimal 16, and hexadecimal 11 is equal to decimal 17. And so on!';
$lang['What is the range of values that can be represented by a Decimal?'] = 'What is the range of values that can be represented by a Decimal?';
$lang['The Decimal system starts with 10 and goes up to 15. This means that the range of values that can be represented by a decimal number is from 0-9, followed by A-F (10-15).'] = 'The Decimal system starts with 10 and goes up to 15. This means that the range of values that can be represented by a decimal number is from 0-9, followed by A-F (10-15).';
$lang['How do you decode Hexadecimal?'] = 'How do you decode Hexadecimal?';
$lang['When it comes to decoding Hexadecimal, there are a few things you need to know. First, just like the decimal system, the hexadecimal system has 10 symbols (0-9) that represent numbers. However, in hexadecimal, these digits have values that are twice as large as their counterparts in the decimal system. So, while the number “10” is represented by the symbol “A” in hexadecimal, it would be equal to “10” in the decimal system.'] = 'When it comes to decoding Hexadecimal, there are a few things you need to know. First, just like the decimal system, the hexadecimal system has 10 symbols (0-9) that represent numbers. However, in hexadecimal, these digits have values that are twice as large as their counterparts in the decimal system. So, while the number “10” is represented by the symbol “A” in hexadecimal, it would be equal to “10” in the decimal system.';
$lang['Similarly, after reaching 9 in Hexadecimal (represented by “F”), we start counting again at 10 (“10”). This pattern continues until we reach 15 (“1F”), at which point we reset back to 0 and begin counting again at 16 (“20”). This might sound confusing at first, but with a little practice, it will become second nature!'] = 'Similarly, after reaching 9 in Hexadecimal (represented by “F”), we start counting again at 10 (“10”). This pattern continues until we reach 15 (“1F”), at which point we reset back to 0 and begin counting again at 16 (“20”). This might sound confusing at first, but with a little practice, it will become second nature!';
$lang['Lastly, just like in base 10 (the decimal system), each place value of a hexadecimal number represents a power of 16. So for example, if we had the number 423004 stored as a hexadecimal value:'] = 'Lastly, just like in base 10 (the decimal system), each place value of a hexadecimal number represents a power of 16. So for example, if we had the number 423004 stored as a hexadecimal value:';
$lang['The 4 would represent 400 (4×100), 2 would represent 20 (2×10), 3 would represent 3 (3×1), and the 0 would represent 0 (0x0).'] = 'The 4 would represent 400 (4×100), 2 would represent 20 (2×10), 3 would represent 3 (3×1), and the 0 would represent 0 (0x0).';
$lang['This is just a basic overview of decoding Hexadecimal numbers. If you’re looking for more detailed information, there are plenty of online resources that can help!'] = 'This is just a basic overview of decoding Hexadecimal numbers. If you’re looking for more detailed information, there are plenty of online resources that can help!';
$lang['Please enter the text to encode into hexadecimal string'] = 'Please enter the text to encode into hexadecimal string';
$lang['from [HEX code] to text'] = 'from [HEX code] to text';
$lang['Normal Text'] = 'Normal Text';
$lang['Enter the normal text to encode'] = 'Enter the normal text to encode';
$lang['Decoded Text'] = 'Decoded Text';
$lang['Enter the decoded text to decode'] = 'Enter the decoded text to decode';
$lang['Space between bytes'] = 'Space between bytes';
$lang['Puts a space between bytes'] = 'Puts a space between bytes';
$lang['Prefix bytes'] = 'Prefix bytes';
$lang['Prepends bytes with 0x'] = 'Prepends bytes with 0x';
$lang['Hexadecimal is a base 16 number system. The numbers 0 through 9 are represented by their corresponding letters (A through F). Numbers from 10 through 15 are represented by two digits, such as 1234 or ABCD. Hexadecimal numbers go beyond these limits, using four characters to represent numbers from 16 through 255.'] = 'Hexadecimal is a base 16 number system. The numbers 0 through 9 are represented by their corresponding letters (A through F). Numbers from 10 through 15 are represented by two digits, such as 1234 or ABCD. Hexadecimal numbers go beyond these limits, using four characters to represent numbers from 16 through 255.';
$lang['Because of browser limitations, your data length could be not over 1950 characters if you would like to use this method directly. Otherwise, please consider using our API'] = 'Because of browser limitations, your data length could be not over 1950 characters if you would like to use this method directly. Otherwise, please consider using our API';
$lang['To encode the text'] = 'To encode the text';
$lang['You may open the browser and load the URL with the parameter like this'] = 'You may open the browser and load the URL with the parameter like this';
$lang['If you would like to encode content of the external URL, you may open the browser and load URL like this'] = 'If you would like to encode content of the external URL, you may open the browser and load URL like this';
$lang['Example'] = 'Example';
$lang['More parameters for encoding your data'] = 'More parameters for encoding your data';
$lang['if you would like to receive the encoded data with the spaces between bytes'] = 'if you would like to receive the encoded data with the spaces between bytes';
$lang['if you would like to receive the result that prepended every byte with 0x'] = 'if you would like to receive the result that prepended every byte with 0x';
$lang['To decode the encoded text'] = 'To decode the encoded text';
$lang['If you would like to decode the external URL, you may open the browser and load URL like this'] = 'If you would like to decode the external URL, you may open the browser and load URL like this';
$lang['if your input is an URL and you would like to encode its content. Without this parameter, our tool would process your URL as text'] = 'if your input is an URL and you would like to encode its content. Without this parameter, our tool would process your URL as text';
$lang['Hexadecimal is a way of representing binary data in human-readable form. It was developed in the 19th century to allow computers to store large amounts of information.'] = 'Hexadecimal is a way of representing binary data in human-readable form. It was developed in the 19th century to allow computers to store large amounts of information.';
$lang['You can use hexadecimal to convert between decimal and binary values. For example, converting 10011011001010 into hexadecimal would result in 0x4F. This means that the value 4F represents the binary number 100110110010110.'] = 'You can use hexadecimal to convert between decimal and binary values. For example, converting 10011011001010 into hexadecimal would result in 0x4F. This means that the value 4F represents the binary number 100110110010110.';
$lang['In mathematics and computer science, hexadecimal (also base 16, or hex) is a positional numeral system with a radix, or base, of 16. It uses sixteen distinct symbols, most often the symbols 0–9 to represent values zero to nine, and A, B, C, D, E, F (or alternatively a–f) to represent values ten to fifteen. For example, the hexadecimal number 2AF3 is equal, in decimal, to (2 × 163) + (10 × 162) + (15 × 161) + (3 × 160) , or 10,995.'] = 'In mathematics and computer science, hexadecimal (also base 16, or hex) is a positional numeral system with a radix, or base, of 16. It uses sixteen distinct symbols, most often the symbols 0–9 to represent values zero to nine, and A, B, C, D, E, F (or alternatively a–f) to represent values ten to fifteen. For example, the hexadecimal number 2AF3 is equal, in decimal, to (2 × 163) + (10 × 162) + (15 × 161) + (3 × 160) , or 10,995.';
$lang['Each hexadecimal digit represents four binary digits (bits) (also called a "nibble"), and the primary use of hexadecimal notation is as a human-friendly representation of binary coded values in computing and digital electronics. For example, byte values can range from 0 to 255 (decimal) but may be more conveniently represented as two hexadecimal digits in the range 00 through FF. Hexadecimal is also commonly used to represent computer memory addresses.'] = 'Each hexadecimal digit represents four binary digits (bits) (also called a "nibble"), and the primary use of hexadecimal notation is as a human-friendly representation of binary coded values in computing and digital electronics. For example, byte values can range from 0 to 255 (decimal) but may be more conveniently represented as two hexadecimal digits in the range 00 through FF. Hexadecimal is also commonly used to represent computer memory addresses.';
$lang['Hex is an abbreviation of Hexadecimal, which is based on a base -16 structure and is used for simplifying how instructions to computers are represented. This 16 symbols number system was developed as a means of inhibiting an 8-bit binary number, so data can be encoded into computers effortlessly. It can be imprinted and typed using two different hex digits with each hex digit demonstrating a nibble or perhaps a 4-bits format.'] = 'Hex is an abbreviation of Hexadecimal, which is based on a base -16 structure and is used for simplifying how instructions to computers are represented. This 16 symbols number system was developed as a means of inhibiting an 8-bit binary number, so data can be encoded into computers effortlessly. It can be imprinted and typed using two different hex digits with each hex digit demonstrating a nibble or perhaps a 4-bits format.';
$lang['This number system uses 16 symbols that are represented in a range from 0-9 or A-F. The 0–9 represent numbers up to nine whereas A-F is represented by the numeric 10–15. As compared to the other three types of number systems, the hexadecimal numeral system is considered to be the most effective one.'] = 'This number system uses 16 symbols that are represented in a range from 0-9 or A-F. The 0–9 represent numbers up to nine whereas A-F is represented by the numeric 10–15. As compared to the other three types of number systems, the hexadecimal numeral system is considered to be the most effective one.';
$lang['Your hexadecimal code is invalid'] = 'Your hexadecimal code is invalid';

// v1.1.0
$lang['Link to GitHub'] = 'Link to GitHub';
$lang['Layout issue on small screen devices'] = 'Layout issue on small screen devices';
$lang['Make text easier to read'] = 'Make text easier to read';
